# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsBookLoader2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import configparser
import os
import ast

class Ui_Settings(object):

    def save_category_synonims(self):
        ''' Save synonims to config variable '''
        synonims_list = []
        synonim = self.category_line.toPlainText()
        synonim = synonim.split(',')
        for syn in synonim:
            try:
                if syn[0] == ' ':
                    syn = syn[1:]
                if syn[-1] == ' ':
                    syn = syn[:-1]
                if not syn in self.cat_list:
                    synonims_list.append(syn)
            except IndexError as e:
                pass

        try:
            if synonims_list != ast.literal_eval(self.category_config.get('Mapper',self.actual_category)):
                self.category_config['Mapper'][self.actual_category] = str(synonims_list)
                self.change = True
        except configparser.NoOptionError as e:
            if synonims_list:
                self.category_config.set('Mapper',self.actual_category,str(synonims_list))
                self.change = True
        except Exception as e:
            pass
        
        self.actual_category = self.category_box.currentText()


    def set_category_mapper(self):
        ''' Set synonims to actual category '''
        try:
            text = ast.literal_eval(self.category_config.get('Mapper', self.category_box.currentText()))
            self.category_line.setText(','.join(text))
        except configparser.NoOptionError as e:
            self.category_line.clear()
        
    def update_category(self):
        ''' Run methods after category change '''
        self.save_category_synonims()
        self.set_category_mapper()

    def update_settings(self):
        ''' Update setting method'''
        # Set MessageBox
        self.msg = QtWidgets.QMessageBox()
        self.msg.setWindowTitle("Ustawienia")

        # Set Parser for config.ini
        config = configparser.ConfigParser()
        config.read(os.path.join(os.path.dirname(__file__), 'config', 'conf.ini'))

        # Save synonims dictionary
        self.save_category_synonims()

        # If Edit lines are empty dont change property
        if not self.isbndb_line.text() == '':
            config['ISBNdb']['token'] = self.isbndb_line.text()
            self.change = True
        if not self.google_line.text() == '':
            config['Google']['token'] = self.google_line.text()
            self.change = True
        if not self.woo_url_line.text() == '':
            config['WooCommerce']['url'] = self.woo_url_line.text()
            self.change = True
        if not self.woo_api_line.text() == '':
            config['WooCommerce']['key'] = self.woo_api_line.text()
            self.change = True
        if not self.woo_secret_line.text() == '':
            config['WooCommerce']['secret'] = self.woo_secret_line.text()
            self.change = True
        if not self.word_url_line.text() == '':
            config['WordPress']['url'] = self.word_url_line.text()
            self.change = True
        if not self.word_user_line.text() == '':
            config['WordPress']['user'] = self.word_user_line.text()
            self.change = True
        if not self.word_pass_line.text() == '':
            config['WordPress']['password'] = self.word_pass_line.text()
            self.change = True

            # Compare checkboxes
        if config.get('Source', 'isbndb') != str(self.isbndb_check_box.isChecked()):
            config['Source']['isbndb'] = str(self.isbndb_check_box.isChecked())
            self.change = True
        if config.get('Source', 'google') != str(self.google_check_box.isChecked()):
            config['Source']['google'] = str(self.google_check_box.isChecked())
            self.change = True
        if config.get('Source', 'amazon') != str(self.amazon_check_box.isChecked()):
            config['Source']['amazon'] = str(self.amazon_check_box.isChecked())
            self.change = True
        if config.get('Source', 'goodreads') != str(self.goodreads_check_box.isChecked()):
            config['Source']['goodreads'] = str(self.goodreads_check_box.isChecked())
            self.change = True

        for radio in self.list_of_radio:
            if radio.isChecked():
                checked_radiobutton = radio.text()
                try:
                    checked_radiobutton = checked_radiobutton.split('.')[0]
                except:
                    pass
                try:
                    checked_radiobutton = checked_radiobutton.split(' ')[0]
                except:
                    pass
        
        if config.get('Validator','priority') != checked_radiobutton.lower():
            config['Validator']['priority'] = checked_radiobutton.lower()
            self.change = True

        if (self.change == False):
            self.msg.setIcon(QtWidgets.QMessageBox.Warning)
            self.msg.setText("Ustawienia nie zostły zaktualizowane")
        else:
            with open(os.path.join(os.path.dirname(__file__), 'config', 'conf.ini'), 'w') as configfile: # Save conf.ini
                config.write(configfile)
            with open(os.path.join(os.path.dirname(__file__), 'config', 'category.ini'), 'w') as configfile: # Save category.ini
                self.category_config.write(configfile)
            self.msg.setIcon(QtWidgets.QMessageBox.Information)
            self.msg.setText("Ustawienia zostły zaktualizowane")
            self.change = False

        self.msg.exec_()


    def setupUi(self, Dialog):
        self.change = False
        config = configparser.ConfigParser()
        config.read(os.path.join(os.path.dirname(__file__),'config', 'conf.ini'))

        self.cat_list = ast.literal_eval(config.get("Category", "categories")) # Get actual list

        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 460)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.isbndb_line = QtWidgets.QLineEdit(Dialog)
        self.isbndb_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.isbndb_line.setFont(font)
        self.isbndb_line.setText("")
        self.isbndb_line.setObjectName("isbndb_line")
        self.gridLayout.addWidget(self.isbndb_line, 0, 2, 1, 3)
        self.word_url_label = QtWidgets.QLabel(Dialog)
        self.word_url_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.word_url_label.setFont(font)
        self.word_url_label.setObjectName("word_url_label")
        self.gridLayout.addWidget(self.word_url_label, 5, 0, 1, 2)
        self.amazon_radio = QtWidgets.QRadioButton(Dialog)
        self.amazon_radio.setObjectName("amazon_radio")
        self.gridLayout.addWidget(self.amazon_radio, 11, 2, 1, 1)
        self.word_pass_line = QtWidgets.QLineEdit(Dialog)
        self.word_pass_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.word_pass_line.setFont(font)
        self.word_pass_line.setText("")
        self.word_pass_line.setObjectName("word_pass_line")
        self.gridLayout.addWidget(self.word_pass_line, 7, 2, 1, 3)
        self.category_box = QtWidgets.QComboBox(Dialog)
        self.category_box.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.category_box.setFont(font)
        self.category_box.setObjectName("category_box")
        for i in range(len(self.cat_list)):
            self.category_box.addItem("")
        self.gridLayout.addWidget(self.category_box, 8, 0, 1, 2)
        self.goodreads_radio = QtWidgets.QRadioButton(Dialog)
        self.goodreads_radio.setObjectName("goodreads_radio")
        self.gridLayout.addWidget(self.goodreads_radio, 11, 3, 1, 1)
        self.isbndb_radio = QtWidgets.QRadioButton(Dialog)
        self.isbndb_radio.setObjectName("isbndb_radio")
        self.gridLayout.addWidget(self.isbndb_radio, 10, 2, 1, 1)
        self.google_check_box = QtWidgets.QCheckBox(Dialog)
        self.google_check_box.setMinimumSize(QtCore.QSize(0, 30))
        self.google_check_box.setObjectName("google_check_box")
        self.gridLayout.addWidget(self.google_check_box, 10, 1, 1, 1)
        self.google_radio = QtWidgets.QRadioButton(Dialog)
        self.google_radio.setObjectName("google_radio")
        self.gridLayout.addWidget(self.google_radio, 10, 3, 1, 1)
        self.word_user_label = QtWidgets.QLabel(Dialog)
        self.word_user_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.word_user_label.setFont(font)
        self.word_user_label.setObjectName("word_user_label")
        self.gridLayout.addWidget(self.word_user_label, 6, 0, 1, 2)
        self.word_user_line = QtWidgets.QLineEdit(Dialog)
        self.word_user_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.word_user_line.setFont(font)
        self.word_user_line.setText("")
        self.word_user_line.setObjectName("word_user_line")
        self.gridLayout.addWidget(self.word_user_line, 6, 2, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 11, 4, 1, 1)
        self.woo_api_label = QtWidgets.QLabel(Dialog)
        self.woo_api_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.woo_api_label.setFont(font)
        self.woo_api_label.setObjectName("woo_api_label")
        self.gridLayout.addWidget(self.woo_api_label, 3, 0, 1, 2)
        self.woo_url_label = QtWidgets.QLabel(Dialog)
        self.woo_url_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.woo_url_label.setFont(font)
        self.woo_url_label.setObjectName("woo_url_label")
        self.gridLayout.addWidget(self.woo_url_label, 2, 0, 1, 2)
        self.woo_api_line = QtWidgets.QLineEdit(Dialog)
        self.woo_api_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.woo_api_line.setFont(font)
        self.woo_api_line.setText("")
        self.woo_api_line.setObjectName("woo_api_line")
        self.gridLayout.addWidget(self.woo_api_line, 3, 2, 1, 3)
        self.woo_secret_line = QtWidgets.QLineEdit(Dialog)
        self.woo_secret_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.woo_secret_line.setFont(font)
        self.woo_secret_line.setText("")
        self.woo_secret_line.setObjectName("woo_secret_line")
        self.gridLayout.addWidget(self.woo_secret_line, 4, 2, 1, 3)
        self.goodreads_check_box = QtWidgets.QCheckBox(Dialog)
        self.goodreads_check_box.setMinimumSize(QtCore.QSize(0, 30))
        self.goodreads_check_box.setChecked(True)
        self.goodreads_check_box.setObjectName("goodreads_check_box")
        self.gridLayout.addWidget(self.goodreads_check_box, 11, 1, 1, 1)
        self.word_url_line = QtWidgets.QLineEdit(Dialog)
        self.word_url_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.word_url_line.setFont(font)
        self.word_url_line.setText("")
        self.word_url_line.setObjectName("word_url_line")
        self.gridLayout.addWidget(self.word_url_line, 5, 2, 1, 3)
        self.isbndb_label = QtWidgets.QLabel(Dialog)
        self.isbndb_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.isbndb_label.setFont(font)
        self.isbndb_label.setObjectName("isbndb_label")
        self.gridLayout.addWidget(self.isbndb_label, 0, 0, 1, 2)
        self.woo_url_line = QtWidgets.QLineEdit(Dialog)
        self.woo_url_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.woo_url_line.setFont(font)
        self.woo_url_line.setText("")
        self.woo_url_line.setObjectName("woo_url_line")
        self.gridLayout.addWidget(self.woo_url_line, 2, 2, 1, 3)
        self.woo_secret_label = QtWidgets.QLabel(Dialog)
        self.woo_secret_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.woo_secret_label.setFont(font)
        self.woo_secret_label.setObjectName("woo_secret_label")
        self.gridLayout.addWidget(self.woo_secret_label, 4, 0, 1, 2)
        self.google_line = QtWidgets.QLineEdit(Dialog)
        self.google_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.google_line.setFont(font)
        self.google_line.setText("")
        self.google_line.setObjectName("google_line")
        self.gridLayout.addWidget(self.google_line, 1, 2, 1, 3)
        self.category_line = QtWidgets.QTextEdit(Dialog)
        self.category_line.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        self.category_line.setFont(font)
        self.category_line.setText("")
        self.category_line.setObjectName("category_line")
        self.gridLayout.addWidget(self.category_line, 8, 2, 1, 3)
        self.word_pass_label = QtWidgets.QLabel(Dialog)
        self.word_pass_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.word_pass_label.setFont(font)
        self.word_pass_label.setObjectName("word_pass_label")
        self.gridLayout.addWidget(self.word_pass_label, 7, 0, 1, 2)
        self.isbndb_check_box = QtWidgets.QCheckBox(Dialog)
        self.isbndb_check_box.setMinimumSize(QtCore.QSize(0, 30))
        self.isbndb_check_box.setObjectName("isbndb_check_box")
        self.gridLayout.addWidget(self.isbndb_check_box, 10, 0, 1, 1)
        self.google_label = QtWidgets.QLabel(Dialog)
        self.google_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.google_label.setFont(font)
        self.google_label.setObjectName("google_label")
        self.gridLayout.addWidget(self.google_label, 1, 0, 1, 2)
        self.amazon_check_box = QtWidgets.QCheckBox(Dialog)
        self.amazon_check_box.setMinimumSize(QtCore.QSize(0, 30))
        self.amazon_check_box.setChecked(True)
        self.amazon_check_box.setObjectName("amazon_check_box")
        self.gridLayout.addWidget(self.amazon_check_box, 11, 0, 1, 1)
        self.priority_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.priority_label.setFont(font)
        self.priority_label.setAlignment(QtCore.Qt.AlignCenter)
        self.priority_label.setObjectName("priority_label")
        self.gridLayout.addWidget(self.priority_label, 9, 2, 1, 2)
        self.sources_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sources_label.setFont(font)
        self.sources_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sources_label.setObjectName("sources_label")
        self.gridLayout.addWidget(self.sources_label, 9, 0, 1, 2)
        
        self.buttonBox.accepted.connect(self.update_settings)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Apply).clicked.connect(self.update_settings)
        self.list_of_radio = [self.amazon_radio,self.goodreads_radio,self.isbndb_radio,self.google_radio]

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.category_config = configparser.ConfigParser()
        self.category_config.optionxform = str
        self.category_config.read(os.path.join(os.path.dirname(__file__), 'config', 'category.ini'))
    
    
        self.set_category_mapper()
        self.actual_category = self.category_box.currentText()
        self.category_box.currentTextChanged.connect(self.update_category)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.word_url_label.setText(_translate("Dialog", "WordPress url link"))
        self.amazon_radio.setText(_translate("Dialog", "Amazon"))
        # self.category_label.setText(_translate("Dialog", "Kategorie"))
        self.goodreads_radio.setText(_translate("Dialog", "Goodreads"))
        self.isbndb_radio.setText(_translate("Dialog", "ISBNDB.COM"))
        self.google_check_box.setText(_translate("Dialog", "Google Books"))
        self.google_radio.setText(_translate("Dialog", "Google Books"))
        self.word_user_label.setText(_translate("Dialog", "WordPress username"))
        self.woo_api_label.setText(_translate("Dialog", "WooCommerce API Key"))
        self.woo_url_label.setText(_translate("Dialog", "WooCommerce url"))
        self.goodreads_check_box.setText(_translate("Dialog", "Goodreads"))
        self.isbndb_label.setText(_translate("Dialog", "ISBNDB API Key"))
        self.woo_secret_label.setText(_translate("Dialog", "WooCommerce Secret Key"))
        self.word_pass_label.setText(_translate("Dialog", "WordPress password"))
        self.isbndb_check_box.setText(_translate("Dialog", "ISBNDB.COM"))
        self.google_label.setText(_translate("Dialog", "Google Books API Key"))
        self.amazon_check_box.setText(_translate("Dialog", "Amazon"))
        self.priority_label.setText(_translate("Dialog", "Priorytet szukania"))
        self.sources_label.setText(_translate("Dialog", "Źródła"))
        for index, cat in enumerate(self.cat_list):
            self.category_box.setItemText(index, _translate("MainWindow", cat))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
